---
title: "Graphics with ggplot2"
author: "Sarah Weiss"
date: "10/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("tidyverse")
library(tidyverse)

#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")

```

Start with the California ('ca') dataset

```{r}
head(ca)
View(ca)
```

Plot visualization to all CA National parks over time
```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors))
```
```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name))
```
```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation")
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") + 
  theme_bw() + #this utilized a different theme
  theme(legend.title = element_blank ()) #this removed the legend title
```

```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = state) ) + 
  labs(x = "Year",
       y = "Visitors", 
       title = "Visitors across State Parks") +
  theme_classic() +
  theme(legend.title = element_blank (),
        axis.text.x = element_text(angle = 45, size = 14))
```

