---
title: "Data Wrangling"
author: "Sarah Weiss"
date: "10/22/2018"
output: html_document
---

## Load Libraries
```{r}
library(tidyverse) # install.packages("tidyverse")
```

## Read data

This is the gapminder dataset

```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

# inspect data set
gapminder # Looks at all the data
head(gapminder) # gives the first 6 by default
tail(gapminder) # gives the last observations, default is 6

head(gapminder, 3)
tail(gapminder, 10)

# summary statistics
str(gapminder)
summary(gapminder)

#install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) # column names
dim(gapminder) # dimensions
ncol(gapminder) # number of columns
nrow(gapminder) # number of rows

#reverse- engineer dim
c(nrow(gapminder), ncol(gapminder))
```

## Dplyr
```{r}
# filter by rows
filter(gapminder, lifeExp < 29)
```

```{r}
# select by columns
select(gapminder, year, lifeExp) # select only these columns
select(gapminder, -continent, -lifeExp) # - will exclude these columns

# use selct and filter together
gap_cambodia <- filter(gapminder, country =="Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)
```

The pipe operator will change your life
```{r}
# this 
gapminder %>% head(3)
#is equivalent to:
head(gapminder, 3)

#let's improve this with pipes!
gap_cambodia <- filter(gapminder, country =="Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

gap_cambodia <- gapminder %>% 
  filter(country = "Cambodia") %>% 
  select(-continent, -lifeExp)
```

```{r}
# mutate adds new variable
gapminder %>% 
  mutate(index = 1:nrow(gapminder))

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

## Challenge:
#Find the maximum gdpPerCap of Egypt and Vietnam. Create a new column. (I want just ine number that is the max of those two countries)

gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp))

```

## group_by() groups!
```{r}
## with mutate()
gap_grouped <- gapminder %>%
  group_by(country) %>%
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp)) %>%
  ungroup()

## with summarize() or summarise()
gap_summarized <- gapminder %>%
  group_by(country) %>%
  mutate(gdp = pop * gdpPercap) %>%
  summarize(max_gdp = max(gdp)) %>%
  ungroup()
```

## arrange() arranges columns
```{r}
gap_summarized <- gapminder %>%
  group_by(country) %>%
  mutate(gdp = pop * gdpPercap) %>%
  summarize(max_gdp = max(gdp)) %>%
  ungroup() %>%
  arrange(desc(max_gdp))
```

## Joining data
```{r}
## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

## explore
co2 %>% head()
co2 %>% dim() # 12 observations

## create a new gapminder variable with only 2007 data
gap_2007 <- gapminder %>%
  filter(year == 2007)

gap_2007 %>% dim() #142 observations

## left_join gap_2007 to co2
lj <- left_join(gap_2007, co2, by = "country")
# another way to write this:
lj <- gap_2007 %>%
  left_join(co2, by = "country")

## right_join gap_2007 to co2
rj <- right_join(gap_2007, co2, by = "country")
# this is the same as 
lj2 <- left_join(co2, gap_2007, by = "country") # but column position is different



```
 
 